baseURL = "https://allen-3.github.io/ninevolt/"
languageCode = "en-us"
title = "Ninevolt"
theme = "hugo-xmin"
relativeURLs = true
canonifyurls = true

enableEmoji = true

# [permalinks]
#     post = "/:slug/"

# Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
# [[menu.main]]
#     name = "Categories"
#     url = "/categories/"
#     weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    footer = "&copy; Allen Sun 2021"

# Taxonomies
[taxonomies]
    tag = "tags"
    category = "categories"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true