baseURL = "https://allen-3.github.io/ninevolt/"
languageCode = "en-us"
title = "Ninevolt"
theme = "hugo-xmin"
relativeURLs = true
canonifyurls = true

enableEmoji = true

# [permalinks]
# post = "/:slug/"
